{--
***************************************


THESE TESTS ARE MOSTLY GENERATED BY AI,
MOSTLY BECAUSE I'M A BIT TOO LAZY TO WRITE THIS MANY TESTS
I DID WRITE THIS TEST RUNNER THOUGH, BUT THAT WAS AT THE START OF THE PROJECT,
RN IT IS PROBABLY A BURDEN, BUT DON'T FEEL LIKE CHANGING IT


**************************************
 -}
import Calc (run)
import Calc.Evaluator (Value (..))
import Calc.Error (EvaluationError (..), LexerError (..), ParserError (..))
import qualified Calc.Error as E
import Data.Bifunctor (first)
import System.Exit (exitFailure, exitSuccess)

-- | An error with its source span stripped, so tests only check the kind of
--   error. The constructor names deliberately match Calc.Error's, so the
--   expectations below read the same as before.
data ErrorKind
  = EvaluationError EvaluationError
  | LexError LexerError
  | ParseError ParserError
  deriving (Show, Eq)

stripSpan :: E.Error -> ErrorKind
stripSpan (E.EvaluationError e _) = EvaluationError e
stripSpan (E.LexError e _)        = LexError e
stripSpan (E.ParseError e _)      = ParseError e

-- A test is: setup lines (run in order, threading the environment through),
-- the input to evaluate afterwards, and the expected number or error.
-- An error in any setup line becomes the result of the whole test.
type Test = ([String], String, Either ErrorKind Double)

-- Runs the setup lines, then the input, and extracts the resulting number.
-- (run falls back to the builtins when the environment is empty.)
evalSession :: [String] -> String -> Either ErrorKind Double
evalSession setup input = first stripSpan (go mempty setup)
  where
    go env [] =
        case run env input of
            Left err             -> Left err
            Right (VNumber n, _) -> Right n
            Right _              -> Left (E.EvaluationError ExpectedNumber Nothing)
    go env (line : rest) = do
        (_, env') <- run env line
        go env' rest

-- Turns a plain "input, expected" pair into a test with no setup.
plain :: (String, Either ErrorKind Double) -> Test
plain (input, expected) = ([], input, expected)

testEval :: [Test] -> IO ()
testEval tests =
    runTests 0 0 tests
  where
    runTests :: Int -> Int -> [Test] -> IO ()
    runTests total passed [] = do
        putStrLn "==============================="
        putStrLn $ show passed ++ " of " ++ show total ++ " tests passed"
        putStrLn "===============================\n"
        if passed == total
            then exitSuccess
            else exitFailure

    runTests total passed ((setup, input, expected) : remaining) =
        let result = evalSession setup input
        in if result == expected
           then do
               putStrLn "- Passed"
               runTests (total + 1) (passed + 1) remaining
           else do
               putStrLn $ "x Test failed:"
               mapM_ (\line -> putStrLn $ " - Setup: " ++ line) setup
               putStrLn $ " - Input: " ++ input
               putStrLn $ " - Expected: " ++ show expected
               putStrLn $ " - Output: " ++ show result
               runTests (total + 1) passed remaining

basicTests :: [(String, Either ErrorKind Double)]
basicTests =
        [ ("2 + 3", Right 5.0)
        , ("2 * 3", Right 6.0)
        , ("2 + 3 * 4", Right 14.0)
        , ("(2 + 3) * 4", Right 20.0)
        , ("10 / 2", Right 5.0)
        , ("10 / 0", Left (EvaluationError DivisionByZero))
        , ("2^2^3", Right 256)

        -- unary minus
        , ("-5", Right (-5.0))
        , ("-5 + 3", Right (-2.0))
        , ("3 + -5", Right (-2.0))
        , ("3 - -5", Right 8.0)
        , ("3 * -5", Right (-15.0))
        , ("-5 * -5", Right 25.0)
        , ("3 / -5", Right (-0.6))
        , ("-2^2", Right (-4.0))       -- unary minus has lower precedence than ^
        , ("(-2)^2", Right 4.0)
        , ("-3 - -3", Right 0.0)
        , ("--5", Right 5.0)

        -- left associativity
        , ("10 - 3 - 2", Right 5.0)          -- would be 9.0 if right-associative
        , ("10 - 3 - 2 - 1", Right 4.0)
        , ("100 / 10 / 2", Right 5.0)        -- would be 20.0 if right-associative
        , ("100 / 5 / 2 / 2", Right 5.0)
        , ("20 - 5 * 2", Right 10.0)
        , ("20 - 10 / 2", Right 15.0)
        , ("2 - 3 + 4", Right 3.0)           -- mixed +/- left-to-right
        , ("2 - 3 + 4 - 1", Right 2.0)

        -- right associativity
        , ("2^3^2", Right 512.0)             -- 2^(3^2) = 2^9, not (2^3)^2 = 64

        -- decimals
        , ("2.5 + 2.5", Right 5.0)
        , ("10.5 / 2", Right 5.25)
        , ("1.5 * 1.5", Right 2.25)

        -- parentheses / nesting
        , ("((2 + 3))", Right 5.0)
        , ("(2 + 3) - (1 + 1)", Right 3.0)
        , ("2 * (3 + (4 - 1))", Right 12.0)
        , ("(10 - 4) / (1 + 2)", Right 2.0)

        -- whitespace handling
        , ("  2   +   3  ", Right 5.0)
        , ("2+3*4", Right 14.0)

        -- errors
        , ("2 + ", Left (ParseError UnexpectedEndOfExpression))
        , ("(2 + 3", Left (ParseError MissingParenthesis))
        , ("2 + 3)", Left (ParseError SyntaxError))
        , ("2 @ 3", Left (LexError (InvalidOperator '@')))
        , ("2..5 + 1", Left (LexError (InvalidNumber "2.")))

        -- trig functions (exact values)
        , ("sin(0)", Right 0.0)
        , ("cos(0)", Right 1.0)
        , ("tan(0)", Right 0.0)

        -- trig functions (compare against Prelude so float rounding can't bite)
        , ("sin(1)", Right (sin 1.0))
        , ("cos(1)", Right (cos 1.0))
        , ("tan(1)", Right (tan 1.0))
        , ("sin(-1)", Right (sin (-1.0)))
        , ("cos(2.5)", Right (cos 2.5))

        -- functions inside expressions
        , ("sin(0) + 3", Right 3.0)
        , ("2 * cos(0)", Right 2.0)
        , ("2 + 3 * cos(0)", Right 5.0)
        , ("cos(0) ^ 3", Right 1.0)
        , ("-cos(0)", Right (-1.0))
        , ("-sin(1)", Right (negate (sin 1.0)))
        , ("cos(0) - -cos(0)", Right 2.0)

        -- arguments that are full expressions
        , ("sin(1 + 1)", Right (sin 2.0))
        , ("cos(2 * 0)", Right 1.0)
        , ("sin((1 + 1) * 2)", Right (sin 4.0))
        , ("cos(sin(0))", Right 1.0)           -- nested functions
        , ("sin(cos(0))", Right (sin 1.0))
        , ("sin(0 - 1)", Right (sin (-1.0)))

        -- whitespace around functions
        , ("sin( 0 )", Right 0.0)
        , ("  cos(0)  ", Right 1.0)

        -- constants
        , ("pi", Right pi)
        , ("e", Right (exp 1))
        , ("2 * pi", Right (2 * pi))
        , ("cos(pi)", Right (cos pi))

        -- function errors
        , ("sin(", Left (ParseError UnexpectedEndOfExpression))
        , ("sin(0", Left (ParseError MissingParenthesis))
        , ("sin()", Left (EvaluationError (InvalidArgumentCount 1 0)))  -- expected, actual
        , ("sin(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("sin", Left (EvaluationError ExpectedNumber))                -- a bare function name is a function value, not a number
        , ("tan(1 / 0)", Left (EvaluationError DivisionByZero))
        , ("foo(1)", Left (EvaluationError (UndefinedFunction "foo")))
        , ("foo", Left (EvaluationError (UndefinedVariable "foo")))

        -- square root and absolute value
        , ("sqrt(0)", Right 0.0)
        , ("sqrt(4)", Right 2.0)
        , ("sqrt(2)^2", Right (sqrt 2.0 ^ (2 :: Int)))
        , ("abs(5)", Right 5.0)
        , ("abs(-5)", Right 5.0)
        , ("abs(0)", Right 0.0)

        -- negate
        , ("negate(5)", Right (-5.0))
        , ("negate(-5)", Right 5.0)
        , ("negate(0)", Right 0.0)

        -- floor, ceil, and round
        , ("floor(3.7)", Right 3.0)
        , ("floor(-3.7)", Right (-4.0))
        , ("floor(3.0)", Right 3.0)
        , ("ceil(3.2)", Right 4.0)
        , ("ceil(-3.2)", Right (-3.0))
        , ("ceil(3.0)", Right 3.0)
        , ("round(3.2)", Right 3.0)
        , ("round(3.8)", Right 4.0)
        , ("round(-3.2)", Right (-3.0))
        , ("round(-3.8)", Right (-4.0))

        -- natural logarithm and logarithm with a base
        , ("ln(1)", Right 0.0)
        , ("ln(e)", Right 1.0)
        , ("ln(exp(2))", Right (log (exp 2.0)))
        , ("log(10, 100)", Right 2.0)
        , ("log(2, 8)", Right 3.0)
        , ("log(10, 1)", Right 0.0)
        , ("log(2, 0.125)", Right (-3.0))

        -- exponential
        , ("exp(0)", Right 1.0)
        , ("exp(1)", Right (exp 1.0))
        , ("exp(2)", Right (exp 2.0))
        , ("ln(exp(3))", Right (log (exp 3.0)))

        -- inverse trigonometric functions (radians)
        , ("asin(0)", Right 0.0)
        , ("asin(1)", Right (asin 1.0))
        , ("asin(-1)", Right (asin (-1.0)))
        , ("acos(1)", Right 0.0)
        , ("acos(0)", Right (acos 0.0))
        , ("acos(-1)", Right (acos (-1.0)))
        , ("atan(0)", Right 0.0)
        , ("atan(1)", Right (atan 1.0))
        , ("atan(-1)", Right (atan (-1.0)))

        -- hyperbolic functions
        , ("sinh(0)", Right 0.0)
        , ("sinh(1)", Right (sinh 1.0))
        , ("sinh(-1)", Right (sinh (-1.0)))
        , ("cosh(0)", Right 1.0)
        , ("cosh(1)", Right (cosh 1.0))
        , ("cosh(-1)", Right (cosh (-1.0)))
        , ("tanh(0)", Right 0.0)
        , ("tanh(1)", Right (tanh 1.0))
        , ("tanh(-1)", Right (tanh (-1.0)))

        -- builtins inside larger expressions
        , ("sqrt(9) + abs(-2)", Right 5.0)
        , ("2 * sqrt(16)", Right 8.0)
        , ("floor(2.9) + ceil(2.1)", Right 5.0)
        , ("exp(ln(5))", Right (exp (log 5.0)))
        , ("sin(asin(0.5))", Right (sin (asin 0.5)))
        , ("cosh(0) + sinh(0)", Right 1.0)
        , ("negate(abs(-3))", Right (-3.0))
        , ("log(2, 8) + sqrt(16)", Right 7.0)

        -- builtin argument count errors
        , ("sqrt()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("sqrt(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("abs()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("negate(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("floor()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("ceil(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("round()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("ln(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("log(10)", Left (EvaluationError (InvalidArgumentCount 2 1)))
        , ("log(2, 8, 16)", Left (EvaluationError (InvalidArgumentCount 2 3)))
        , ("exp()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("asin(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("acos()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("atan(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("sinh()", Left (EvaluationError (InvalidArgumentCount 1 0)))
        , ("cosh(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))
        , ("tanh()", Left (EvaluationError (InvalidArgumentCount 1 0)))

        -- implicit multiplication (NOT IMPLEMENTED YET: these fail until it is)
        , ("2(3)", Right 6.0)
        , ("(2)(3)", Right 6.0)
        , ("(2 + 3)(4 + 5)", Right 45.0)
        , ("2 cos(0)", Right 2.0)
        , ("2cos(0)", Right 2.0)
        , ("(2)cos(0)", Right 2.0)
        , ("cos(0)(2)", Right 2.0)
        , ("sin(0) cos(0)", Right 0.0)

        -- two bare numbers should still be an error even with implicit multiplication
        , ("2 3", Left (ParseError SyntaxError))
        , ("cos(0)2", Left (ParseError SyntaxError))
        ]

-- Each test: (setup lines, input, expected)
functionTests :: [Test]
functionTests =
    [ -- basic definition and call
      (["f(x) = x * 2"], "f(3)", Right 6.0)
    , (["f(x)=x*2"], "f(3)", Right 6.0)                 -- no spaces
    , (["f( x ) = x * 2"], "f( 3 )", Right 6.0)         -- extra spaces
    , (["f(x) = x ^ 2"], "f(4)", Right 16.0)

    -- multiple parameters
    , (["add(x, y) = x + y"], "add(2, 3)", Right 5.0)
    , (["sub(x, y) = x - y"], "sub(10, 4)", Right 6.0)  -- argument order matters
    , (["vol(a, b, c) = a * b * c"], "vol(2, 3, 4)", Right 24.0)

    -- arguments can be full expressions
    , (["f(x) = x * 2"], "f(1 + 2)", Right 6.0)
    , (["f(x) = x * 2"], "f(2 * 3 - 1)", Right 10.0)
    , (["f(x) = x * 2"], "f(-3)", Right (-6.0))

    -- calls inside expressions
    , (["f(x) = x + 1"], "f(2) ^ 2", Right 9.0)
    , (["f(x) = x + 1"], "2 * f(3)", Right 8.0)
    , (["f(x) = x + 1"], "-f(2)", Right (-3.0))
    , (["f(x) = x ^ 2"], "f(2) + f(3)", Right 13.0)

    -- nested calls
    , (["f(x) = x + 1"], "f(f(1))", Right 3.0)
    , (["f(x) = x * 2", "g(x) = x + 1"], "f(g(3))", Right 8.0)

    -- functions calling other user-defined functions
    , (["f(x) = x * 2", "g(x) = f(x) + 1"], "g(3)", Right 7.0)

    -- builtins and constants inside bodies
    , (["f(x) = sin(x)"], "f(0)", Right 0.0)
    , (["f(x) = cos(x) + 1"], "f(0)", Right 2.0)
    , (["f(r) = 2 * pi * r"], "f(1)", Right (2 * pi))

    -- user-defined constants inside bodies
    , (["k = 10", "f(x) = x * k"], "f(3)", Right 30.0)

    -- parameters shadow outer constants
    , (["x = 100", "f(x) = x + 1"], "f(1)", Right 2.0)

    -- the constant outside is untouched by a call
    , (["x = 100", "f(x) = x + 1", "f(1)"], "x", Right 100.0)

    -- redefinition replaces the old function
    , (["f(x) = x", "f(x) = x * 10"], "f(2)", Right 20.0)

    -- errors
    , (["f(x) = x"], "f(1, 2)", Left (EvaluationError (InvalidArgumentCount 1 2)))  -- expected, actual
    , (["f(x, y) = x + y"], "f(1)", Left (EvaluationError (InvalidArgumentCount 2 1)))
    , (["f(x) = x"], "f()", Left (EvaluationError (InvalidArgumentCount 1 0)))
    , (["f(x) = x + y"], "f(1)", Left (EvaluationError (UndefinedVariable "y")))
    , ([], "g(1)", Left (EvaluationError (UndefinedFunction "g")))
    , (["f(x) = x"], "f", Left (EvaluationError ExpectedNumber))  -- a bare function name is not a number
    , (["f(x, x) = x"], "1", Left (ParseError (DuplicateParameter "x")))
    ]

-- Functions passed as arguments to other functions
higherOrderTests :: [Test]
higherOrderTests =
    [ -- passing builtins
      (["apply(f, x) = f(x)"], "apply(sin, 0)", Right 0.0)
    , (["apply(f, x) = f(x)"], "apply(cos, 0)", Right 1.0)

    -- passing user-defined functions
    , (["double(x) = x * 2", "apply(f, x) = f(x)"], "apply(double, 4)", Right 8.0)

    -- the passed function is called more than once
    , (["inc(x) = x + 1", "twice(f, x) = f(f(x))"], "twice(inc, 5)", Right 7.0)

    -- composing two passed functions (order matters: f(g(x)))
    , (["inc(x) = x + 1", "double(x) = x * 2", "compose(f, g, x) = f(g(x))"],
       "compose(inc, double, 5)", Right 11.0)
    , (["inc(x) = x + 1", "double(x) = x * 2", "compose(f, g, x) = f(g(x))"],
       "compose(double, inc, 5)", Right 12.0)

    -- a call to a higher-order function inside a larger expression
    , (["inc(x) = x + 1", "twice(f, x) = f(f(x))"], "2 * twice(inc, 1) + 1", Right 7.0)

    -- errors
    , (["apply(f, x) = f(x)"], "apply(nope, 1)", Left (EvaluationError (UndefinedVariable "nope")))
    , (["apply(f, x) = f(x)"], "apply(sin, 1, 2)", Left (EvaluationError (InvalidArgumentCount 2 3)))
    ]

main :: IO ()
main = testEval (map plain basicTests ++ functionTests ++ higherOrderTests)
